use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

def shared_pods
  pod 'C3Lib', :path => '../'
end

target 'C3Lib_Example' do
  shared_pods
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'IGIdenticon', '~> 0.4'
  pod 'JSQMessagesViewController', '~> 7.3.4'
  pod 'JTSImageViewController', '~> 1.5.1'
  pod 'KeyboardObserver', '~> 1.0.1'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'SVPullToRefresh', '~> 0.4.1'
end
