use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

def shared_pods
  pod 'C3Lib', :path => '../'
end

target 'C3Lib_Example' do
  shared_pods
  pod 'IGIdenticon'
  pod 'JSQMessagesViewController'
  pod 'KeyboardObserver'
  pod 'SDWebImage'
end
